name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar flag
        id: flag
        run: |
          echo "YSBhdWxh" > flag.txt

      - name: Expor resultado
        run: cat flag.txt